### ISSUE TITLE
Please add support for recent versions of optparse-applicative

### ISSUE THREAD

**Issue by peti** [frasertweedale/hs-persona-idp#1]
We would like to package 'persona-idp' in NixOS, but we have only current version of `optparse-applicative`. Would it be possible to update the supported versions of your library's dependencies? http://packdeps.haskellers.com/feed?needle=persona-idp

**Comment by frasertweedale** [comment]
@peti, thanks for packaging it!  I'm on it.

**Comment by frasertweedale** [comment]
Fixed in v0.1.0.2.  Let me know if you have any further issues and thanks again!
