### ISSUE TITLE
I think persona-idp has an incompatible depedency when using GHC 7.10.1

### ISSUE THREAD

**Issue by nogweii** [frasertweedale/hs-persona-idp#2]
Using Archlinux, running `cabal install persona-idp' results in:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: persona-idp-0.1.0.2 (user goal)
trying: jose-0.3.41.1 (dependency of persona-idp-0.1.0.2)
trying: x509-1.5.0.1 (dependency of persona-idp-0.1.0.2)
trying: process-1.2.3.0/installed-3b1... (dependency of x509-1.5.0.1)
next goal: unix (dependency of persona-idp-0.1.0.2)
rejecting: unix-2.7.1.0/installed-e59... (conflict: unix =>
time==1.5.0.1/installed-e17..., jose => time==1.4.*)
rejecting: unix-2.7.1.0, 2.7.0.1, 2.7.0.0, 2.6.0.1, 2.6.0.0, 2.5.1.1, 2.5.1.0,
2.5.0.0, 2.4.2.0, 2.4.1.0, 2.4.0.2, 2.4.0.1, 2.4.0.0, 2.3.2.0, 2.3.1.0,
2.3.0.0, 2.2.0.0, 2.0 (conflict: process => unix==2.7.1.0/installed-e59...)
Dependency tree exhaustively searched.
```

GHC version 7.10.1, Cabal 1.22.0.1 (and 1.22.4.0, I just updated)

**Comment by nogweii** [comment]
Ah, thinking about it a little more, I think it's because https://github.com/frasertweedale/hs-jose/commit/cfa685b8a6778323ac9e3da4be55369e1dff7d85 hasn't been pushed to hackage yet.

**Comment by frasertweedale** [comment]
That's right.  I'll cut v0.1.0.3 and upload to hackage in the next day or so.  Thanks!

**Comment by frasertweedale** [comment]
Oh wait, it's jose.  Oh I'll cut a new release of jose and upload _that_ to hackage instead :)

**Comment by frasertweedale** [comment]
OK I released https://hackage.haskell.org/package/jose-0.3.41.2 so should be OK now.  Let me know if you have any other troubles and thanks for reporting :)
